import { mutation } from "./_generated/server";

export const seed = mutation({
  handler: async (ctx) => {
    const now = new Date().toISOString();

    const properties = [
      { title: "3 Bedroom Apartment in Lekki Phase 1", property_type: "apartment", listing_type: "rent", status: "available", price: 3500000, currency: "NGN", price_period: "yearly", bedrooms: 3, bathrooms: 2, sqft: 1800, address: "12 Admiralty Way, Lekki Phase 1", city: "Lekki", state: "Lagos", description: "Spacious 3 bedroom apartment with modern finishes, fitted kitchen, and 24hr power supply. Gated estate with swimming pool.", features: ["Swimming Pool", "Gym", "24hr Power", "Security"] },
      { title: "4 Bedroom Duplex in Ikoyi", property_type: "house", listing_type: "sale", status: "available", price: 180000000, currency: "NGN", price_period: "one-time", bedrooms: 4, bathrooms: 4, sqft: 3200, address: "8 Bourdillon Road, Ikoyi", city: "Ikoyi", state: "Lagos", description: "Luxury 4 bedroom semi-detached duplex with BQ, swimming pool, and private garden. Prime Ikoyi location.", features: ["BQ", "Swimming Pool", "Garden", "Smart Home"] },
      { title: "2 Bedroom Flat in Ajah", property_type: "apartment", listing_type: "rent", status: "available", price: 1500000, currency: "NGN", price_period: "yearly", bedrooms: 2, bathrooms: 2, sqft: 1200, address: "5 Abraham Adesanya Estate, Ajah", city: "Ajah", state: "Lagos", description: "Newly built 2 bedroom flat in a serene estate. Close to Ajah bus stop and shopping centers.", features: ["Parking", "Security", "Water Supply"] },
      { title: "5 Bedroom Mansion in Banana Island", property_type: "house", listing_type: "sale", status: "available", price: 850000000, currency: "NGN", price_period: "one-time", bedrooms: 5, bathrooms: 6, sqft: 5500, address: "3 Banana Island Road", city: "Banana Island", state: "Lagos", description: "Ultra luxury 5 bedroom mansion on Banana Island with waterfront views, cinema room, and infinity pool.", features: ["Waterfront", "Cinema", "Infinity Pool", "Elevator", "Smart Home"] },
      { title: "1 Bedroom Studio in Victoria Island", property_type: "apartment", listing_type: "rent", status: "available", price: 2000000, currency: "NGN", price_period: "yearly", bedrooms: 1, bathrooms: 1, sqft: 650, address: "14 Adeola Odeku Street, VI", city: "Victoria Island", state: "Lagos", description: "Modern studio apartment perfect for young professionals. Walking distance to offices and restaurants.", features: ["Furnished", "24hr Power", "Gym"] },
      { title: "3 Bedroom Terrace in Surulere", property_type: "house", listing_type: "sale", status: "available", price: 45000000, currency: "NGN", price_period: "one-time", bedrooms: 3, bathrooms: 3, sqft: 2000, address: "22 Bode Thomas Street, Surulere", city: "Surulere", state: "Lagos", description: "Newly renovated 3 bedroom terrace duplex in the heart of Surulere. Close to National Stadium.", features: ["Parking", "Security", "Modern Kitchen"] },
      { title: "4 Bedroom Semi-Detached in Magodo", property_type: "house", listing_type: "sale", status: "available", price: 75000000, currency: "NGN", price_period: "one-time", bedrooms: 4, bathrooms: 3, sqft: 2800, address: "7 CMD Road, Magodo Phase 2", city: "Magodo", state: "Lagos", description: "Well finished 4 bedroom semi-detached duplex with spacious compound and BQ in Magodo GRA Phase 2.", features: ["BQ", "Spacious Compound", "Security"] },
      { title: "2 Bedroom Apartment in Yaba", property_type: "apartment", listing_type: "rent", status: "available", price: 1200000, currency: "NGN", price_period: "yearly", bedrooms: 2, bathrooms: 1, sqft: 950, address: "15 Herbert Macaulay Way, Yaba", city: "Yaba", state: "Lagos", description: "Affordable 2 bedroom flat in Yaba tech hub area. Close to UNILAG and Yaba College of Tech.", features: ["Parking", "Water Supply"] },
      { title: "Commercial Office Space in Ikeja GRA", property_type: "commercial", listing_type: "lease", status: "available", price: 8000000, currency: "NGN", price_period: "yearly", bedrooms: 0, bathrooms: 2, sqft: 2500, address: "4 Joel Ogunnaike Street, Ikeja GRA", city: "Ikeja", state: "Lagos", description: "Premium open-plan office space in Ikeja GRA. Suitable for corporate offices with reception area and conference room.", features: ["Reception", "Conference Room", "24hr Power", "Parking"] },
      { title: "3 Bedroom Flat in Gbagada", property_type: "apartment", listing_type: "rent", status: "available", price: 2000000, currency: "NGN", price_period: "yearly", bedrooms: 3, bathrooms: 2, sqft: 1500, address: "10 Diya Street, Gbagada Phase 2", city: "Gbagada", state: "Lagos", description: "Spacious 3 bedroom flat in a quiet area of Gbagada Phase 2. Family friendly neighborhood.", features: ["Parking", "Security", "Water Supply"] },
      { title: "Land in Ibeju-Lekki (500sqm)", property_type: "land", listing_type: "sale", status: "available", price: 15000000, currency: "NGN", price_period: "one-time", bedrooms: 0, bathrooms: 0, sqft: 5382, address: "Eleranigbe, Ibeju-Lekki", city: "Ibeju-Lekki", state: "Lagos", description: "500sqm dry land in fast developing Ibeju-Lekki axis. Near Dangote Refinery and new Lekki Airport.", features: ["Dry Land", "C of O", "Good Road"] },
      { title: "4 Bedroom Penthouse in Eko Atlantic", property_type: "apartment", listing_type: "sale", status: "available", price: 350000000, currency: "NGN", price_period: "one-time", bedrooms: 4, bathrooms: 4, sqft: 4000, address: "Azuri Peninsula, Eko Atlantic City", city: "Eko Atlantic", state: "Lagos", description: "Premium penthouse in Eko Atlantic City with panoramic ocean views. World class finishing and amenities.", features: ["Ocean View", "Concierge", "Gym", "Pool", "Smart Home"] },
      { title: "2 Bedroom Apartment in Sangotedo", property_type: "apartment", listing_type: "rent", status: "available", price: 900000, currency: "NGN", price_period: "yearly", bedrooms: 2, bathrooms: 2, sqft: 1100, address: "Shapati Road, Sangotedo", city: "Sangotedo", state: "Lagos", description: "Budget friendly 2 bedroom apartment in Sangotedo. Close to Shoprite and Novare Mall.", features: ["Parking", "Security"] },
      { title: "5 Bedroom Mansion in Osapa London", property_type: "house", listing_type: "sale", status: "available", price: 120000000, currency: "NGN", price_period: "one-time", bedrooms: 5, bathrooms: 5, sqft: 4200, address: "6 Osapa London Estate, Lekki", city: "Osapa London", state: "Lagos", description: "Massive 5 bedroom fully detached duplex with BQ, swimming pool, and large compound in Osapa London.", features: ["BQ", "Swimming Pool", "Large Compound", "Security"] },
      { title: "3 Bedroom Apartment in Oniru", property_type: "apartment", listing_type: "rent", status: "available", price: 5000000, currency: "NGN", price_period: "yearly", bedrooms: 3, bathrooms: 3, sqft: 2200, address: "2 Palace Road, Oniru Estate", city: "Oniru", state: "Lagos", description: "Luxury 3 bedroom apartment in Oniru Estate with ocean view. Fully serviced with 24hr power.", features: ["Ocean View", "24hr Power", "Gym", "Pool", "Serviced"] },
      { title: "1 Bedroom Mini Flat in Maryland", property_type: "apartment", listing_type: "rent", status: "available", price: 800000, currency: "NGN", price_period: "yearly", bedrooms: 1, bathrooms: 1, sqft: 500, address: "8 Mobolaji Bank Anthony Way, Maryland", city: "Maryland", state: "Lagos", description: "Clean 1 bedroom mini flat in Maryland. Easy access to Ikeja and the Island via Third Mainland Bridge.", features: ["Parking", "Water Supply"] },
      { title: "Warehouse in Apapa", property_type: "commercial", listing_type: "lease", status: "available", price: 25000000, currency: "NGN", price_period: "yearly", bedrooms: 0, bathrooms: 1, sqft: 10000, address: "Wharf Road, Apapa", city: "Apapa", state: "Lagos", description: "Large warehouse space near Apapa port. Ideal for import/export businesses and logistics companies.", features: ["Loading Bay", "Security", "Generator"] },
      { title: "3 Bedroom Bungalow in Festac", property_type: "house", listing_type: "sale", status: "available", price: 35000000, currency: "NGN", price_period: "one-time", bedrooms: 3, bathrooms: 2, sqft: 1800, address: "23 4th Avenue, Festac Town", city: "Festac", state: "Lagos", description: "Solid 3 bedroom bungalow on a full plot in Festac Town. Good for family living or redevelopment.", features: ["Full Plot", "Fenced", "Security"] },
      { title: "4 Bedroom Townhouse in VGC", property_type: "house", listing_type: "sale", status: "available", price: 95000000, currency: "NGN", price_period: "one-time", bedrooms: 4, bathrooms: 4, sqft: 3000, address: "12 1st Avenue, VGC", city: "VGC", state: "Lagos", description: "Beautiful 4 bedroom townhouse in Victoria Garden City. Gated community with excellent amenities.", features: ["Gated Community", "Gym", "Pool", "Tennis Court", "Security"] },
      { title: "Land in Lakowe (800sqm)", property_type: "land", listing_type: "sale", status: "available", price: 12000000, currency: "NGN", price_period: "one-time", bedrooms: 0, bathrooms: 0, sqft: 8611, address: "Lakowe Lake Golf Estate", city: "Lakowe", state: "Lagos", description: "800sqm land in the prestigious Lakowe Lake Golf Estate. Fully serviced with golf course access.", features: ["Golf Course", "Serviced", "C of O", "Good Road"] },
    ];

    let count = 0;
    for (const p of properties) {
      await ctx.db.insert("properties", {
        ...p,
        created_at: now,
        updated_at: now,
      });
      count++;
    }

    return { seeded: count };
  },
});
